UNARY_OPERATOR = set()

ARITHMETIC_OPERATOR = {
    'PLUS',
    'MINUS',
    'TIMES',
    'DIVIDE'
}

LOGICAL_OPERATOR = {
    'LESS_THAN',
    'GREATER_THAN',
    'LESS_EQUALS_THAN',
    'GREATER_EQUALS_THAN',
    'EQ_COMPARISON',
    'INEQ_COMPARISON'
}

BINARY_OPERATOR = LOGICAL_OPERATOR | ARITHMETIC_OPERATOR

TYPE = {'TYPE'}

IDENTIFIER = {'IDENTIFIER'}

ASSIGN = {'ASSIGN'}

PARENTHESIS = {
    'L_PAREN',
    'R_PAREN',
}

tokens = UNARY_OPERATOR | BINARY_OPERATOR | TYPE | IDENTIFIER | ASSIGN | PARENTHESIS
